import puppeteer from 'file:///C:/Users/noelf/Documents/GitHub/turtles_project/turtles_frontend/node_modules/puppeteer-core/lib/esm/puppeteer/puppeteer-core.js';
const wait = ms => new Promise(r => setTimeout(r, ms));
const browser = await puppeteer.launch({ executablePath: 'C:/Program Files/Google/Chrome/Application/chrome.exe', headless: 'new' });
const page = await browser.newPage();
const errs=[]; page.on('pageerror',e=>errs.push('pageerror: '+e.message)); page.on('console',m=>{if(m.type()==='error')errs.push('console: '+m.text());});
await page.goto('http://localhost:8099/index.html?x='+Date.now(), { waitUntil:'networkidle0' });
await page.type('#gatePassword','cafe2026'); await page.click('#gateForm button[type=submit]'); await wait(700);
console.log('sync            :', await page.$eval('#syncText', e=>e.textContent));
console.log('subtitulo       :', await page.$eval('.brand-text p', e=>e.textContent));
console.log('botao decidir   :', await page.$eval('#decideBtn', e=>e.textContent));
console.log('team stats[jorge]:', await page.$$eval('.person-row', els => { const r=els.find(e=>e.textContent.includes('JORGE')); return r?r.querySelector('.person-stats').textContent:'?';}));
console.log('ranking (ordem) :', await page.$$eval('.fair-row', els=>els.map(e=>e.querySelector('.fair-name').textContent+' '+e.querySelector('.fair-pct').textContent).join(' | ')));
console.log('badges hoje     :', await page.$$eval('.sel-row', els=>els.map(e=>e.querySelector('.sel-name').textContent+':'+e.querySelector('.sel-badge').textContent).join(' | ')));
console.log('--- stats tiles ---');
console.log(await page.$$eval('.summary-tile', els=>els.map(e=>e.querySelector('.summary-label').textContent+'='+e.querySelector('strong').textContent+(e.querySelector('.summary-sub')?' ('+e.querySelector('.summary-sub').textContent+')':'')).join('\n')));
console.log('--- decidir com todos ---');
await page.click('#selAllBtn'); await wait(300);
await page.click('#decideBtn'); await wait(1200);
console.log('vencedor        :', await page.$eval('#winnerName', e=>e.textContent));
console.log('team stats apos :', await page.$$eval('.person-row', els=>els.map(e=>e.querySelector('.person-name').textContent+'['+e.querySelector('.person-stats').textContent+']').join(' ')));
console.log('rondas tile     :', await page.$$eval('.summary-tile', els=>{const r=els.find(e=>e.querySelector('.summary-label').textContent==='rondas');return r.querySelector('strong').textContent;}));
console.log('ERROS:', errs.length?errs:'nenhum');
await browser.close();
